{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ template "base-chart.name" . }}
  labels:
    app: {{ template "base-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.deployment.labels }}
  {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecret.region }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "base-chart.name" . }}
  labels:
    app: {{ template "base-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.deployment.labels }}
  {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  refreshInterval: "{{ .Values.externalSecret.refreshInterval }}"
  secretStoreRef:
    name: {{ template "base-chart.name" . }}
    kind: SecretStore
  target:
    name: {{ template "base-chart.name" . }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.externalSecret.env }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value }}
  {{- end }}
{{- end }}