{{- if and .Values.autoscaler.enabled .Values.autoscaler.autoscaleMin .Values.autoscaler.autoscaleMax }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "base-chart.name" . }}-cpu-mem
  labels:
    app: {{ template "base-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "base-chart.name" . }}
  minReplicas: {{ .Values.autoscaler.autoscaleMin }}
  maxReplicas: {{ .Values.autoscaler.autoscaleMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaler.cpu.targetAverageUtilization }}
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: {{ .Values.autoscaler.memory.targetAverageValue }}
---
{{- end }}
