apiVersion: v1
kind: Service
metadata:
  name: {{ template "base-chart.name" . }}
  labels:
    app: {{ template "base-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
  {{- if .Values.service }}
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.serverPort }}
      targetPort: {{ if .Values.service.targetPort }}{{ .Values.service.targetPort }}{{ else }}{{ .Values.service.serverPort }}{{ end }}
      name: {{ .Values.service.serverPortName }}
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.admin.nodePort }}
  {{- end }}
  {{ if .Values.service.managementPort }}
    - port: {{ .Values.service.managementPort }}
      targetPort: {{ .Values.service.managementPort }}
      name: {{ .Values.service.managementPortName }}
  {{- end }}
  selector:
    app: {{ template "base-chart.name" . }}
    release: {{ .Release.Name | quote }}
