{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "base-chart.name" . }}-serviceaccount
  labels:
    app: {{ template "base-chart.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  {{- if .Values.deployment.labels }}
  {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  annotations:
  {{- if .Values.deployment.annotations }}
  {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.serviceAccount.awsRole (ne .Values.serviceAccount.awsRole "false") -}}
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s" .Values.serviceAccount.awsAccount .Values.serviceAccount.awsRole }}
  {{- end }}
{{- end -}}