base-chart:

  extraEnv:
    ANODOT_EVENT_CONFIG_LOCATION: "/mnt/config.yaml"    
    ANODOT_EVENT_CATEGORY: "kube-events-test"
    ANODOT_EVENT_SOURCE: "kube-events-test"
    ANODOT_LOG_LEVEL: 5
    ANODOT_HTTP_DEBUG_ENABLED: "true"
    ANODOT_URL: "https://master.ano-dev.com"
    ANODOT_ACCESS_KEY: "test-events"

  externalSecret:
    enabled: true
    env:
      ANODOT_API_TOKEN: "/dev/kube-events/ANODOT_API_TOKEN"
    refreshInterval: "1h"
    region: us-east-1
    backendType: systemManager


  ingress:
    enabled: true
    className: internal
    # annotations:
    #   kubernetes.io/ingress.class: internal
    paths: /
    hosts:
      - anodot-kube-events.dev-int.mypileus.io

  configmap:
    enabled: true
    mountPath: /mnt/
    data:
      config.yaml: |-
        deployment:
          enabled: true
          namespace: default
          eventConfig:
            category: kube-events-test