base-chart:

  extraEnv:
    # EXCLUDE_NAMESPACE: "kube-system"
    # INCLUDE_LABELS

  ingress:
    enabled: true
    className: internal
    # annotations:
    #   kubernetes.io/ingress.class: internal
    paths: /
    hosts:
      - anodot-kube-events.prod-int.mypileus.io
