base-chart:
  nameOverride: anodot-kube-events
  image:
    repository: 932213950603.dkr.ecr.us-east-1.amazonaws.com/anodot-kube-events
    tag: 0.0.9

  replicaCount: 1

  javaConfig:
    enabled: false

  # extraEnv:


  resources:
    # limits:
      #cpu: 2000m
      # memory: 4000M
    requests:
      cpu: 50m
      memory: 1800M

  service:
    serverPort: 8080
    serverPortName: http
    managementPort: 8888
    managementPortName: http-management
    targetPort: http
    labels:
      version: v1
    # annotations:
    #   key: value
    type: ClusterIP

  ingress:
    enabled: false
    className: internal
    # annotations:
    #   kubernetes.io/ingress.class: internal
    paths: /
    # hosts:
    #   - app-name.dev-int.mypileus.io

  clusterRole:
    enabled: true
    name: kube-events-role
    rules:
      - apiGroups: [""]
        resources: ["pods", "replicasets", "deployments", "daemonsets", "nodes"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["apps"]
        resources: ["replicasets", "deployments", "daemonsets"]
        verbs: ["get", "list", "watch"]

  clusterRoleBinding:
    enabled: true
    name: kube-events-role-binding
    roleName: kube-events-role
    serviceAccountName: anodot-kube-events-serviceaccount
    namespace: anodot-kube-events